import 'package:flutter/material.dart';

enum AppLanguage { en, pl, nl, tr, bg, el }
enum AppUiScale { normal, large, largest }

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  static AppStrings of(BuildContext context) {
    return AppStrings(Localizations.localeOf(context));
  }

  static const Map<AppLanguage, Locale> supportedLanguageLocales = {
    AppLanguage.en: Locale('en'),
    AppLanguage.pl: Locale('pl'),
    AppLanguage.nl: Locale('nl'),
    AppLanguage.tr: Locale('tr'),
    AppLanguage.bg: Locale('bg'),
    AppLanguage.el: Locale('el'),
  };

  static List<Locale> supportedLocales() {
    return supportedLanguageLocales.values.toList();
  }

  static AppLanguage fromLocale(Locale locale) {
    return supportedLanguageLocales.entries
            .firstWhere(
              (entry) => entry.value.languageCode == locale.languageCode,
              orElse: () => const MapEntry(AppLanguage.en, Locale('en')),
            )
            .key;
  }

  static String languageLabel(AppLanguage language) {
    switch (language) {
      case AppLanguage.en:
        return '🇬🇧 English';
      case AppLanguage.pl:
        return '🇵🇱 Polski';
      case AppLanguage.nl:
        return '🇳🇱 Nederlands';
      case AppLanguage.tr:
        return '🇹🇷 Turkce';
      case AppLanguage.bg:
        return '🇧🇬 Balgarski';
      case AppLanguage.el:
        return '🇬🇷 Ellinika';
    }
  }

  static String uiScaleLabel(AppUiScale scale, String languageCode) {
    // krótkie, nie-tłumaczone napisy – ważniejsza czytelność niż pełna lokalizacja
    switch (scale) {
      case AppUiScale.normal:
        return 'A';
      case AppUiScale.large:
        return 'A+';
      case AppUiScale.largest:
        return 'A++';
    }
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'appTitle': 'CMMS LCS CLEAN',
      'loginTitle': 'Sign in',
      'username': 'Username',
      'password': 'Password',
      'login': 'Login',
      'enterUsername': 'Enter username',
      'enterPassword': 'Enter password',
      'machines': 'CMMS Ultimo - Machines',
      'addMachine': 'Add machine',
      'cancel': 'Cancel',
      'save': 'Save',
      'name': 'Name',
      'code': 'Code',
      'location': 'Location',
      'description': 'Description',
      'emptyList': 'No machines yet. Add your first item.',
      'dbErrorTitle': 'Database loading error.',
      'logout': 'Logout',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'language': 'Language',
      'requiredField': 'Required field',
      'uiScale': 'Interface size',
      'loginFailed': 'Invalid username or password',
      'reportFailure': 'Report failure',
      'users': 'Users',
      'addUser': 'Add user',
      'noUsers': 'No users yet.',
      'admin': 'Admin',
      'userExists': 'User already exists.',
      'permManageAssets': 'Manage assets',
      'permReportFailure': 'Report failures',
      'permManageUsers': 'Manage users',
      'manageUsers': 'Manage users and permissions',
      'reportSaved': 'Report saved locally.',
      'photoPath': 'Photo path (optional)',
      'whatHappened': 'What happened?',
      'lineName': 'Production line',
      'resolvedQuestion': 'Was the issue resolved?',
      'fixDuration': 'Fix duration',
      'whatFixed': 'What was fixed?',
      'whoFixed': 'Who fixed it?',
      'quickActions': 'Quick actions',
      'machinesTile': 'Assets / Machines',
      'usersTile': 'Users',
      'reportFailureTile': 'Report failure',
      'dashboardTitle': 'Dashboard',
      'menuTitle': 'Menu',
      'homeTitle': 'Home',
      'openFailures': 'Open',
      'closedFailures': 'Resolved',
      'totalDowntime': 'Downtime (h)',
      'efficiency': 'Efficiency',
      'failuresByLine': 'Failures by line',
      'topContributors': 'Top reporters',
      'topFixers': 'Top fixers',
      'photoStep': 'Step 1: Take/Add Photo',
      'formStep': 'Step 2: Failure Details',
      'takePhoto': 'Take Photo',
      'pickPhoto': 'Pick from Gallery',
      'reason': 'Reason',
      'priority': 'Priority',
      'reporter': 'Reporter',
      'status': 'Status',
      'open': 'OPEN',
      'closed': 'CLOSED',
      'repairStart': 'Repair Start',
      'repairEnd': 'Repair End',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'critical': 'Critical',
      'downtime': 'Downtime',
      'hours': 'h',
      'minutes': 'm',
      'days': 'd',
      'history': 'History',
      'filterHint': 'Search by ID, line, location...',
      'all': 'All',
      'currentFailures': 'Current Failures',
      'dateFrom': 'From Date',
      'dateTo': 'To Date',
      'downloadReport': 'Download Report',
      'closeFailure': 'Close Failure',
      'yearly': 'Yearly',
      'customRange': 'Custom Range',
      'documentation': 'Documentation',
      'addDocumentation': 'Add Documentation',
      'warehouse': 'Warehouse',
      'schedule': 'Schedule',
      'productionList': 'Storing List',
      'chat': 'Chat',
      'onlineUsers': 'Online Users',
      'role': 'Role',
      'other': 'Other',
      'quantity': 'Quantity',
      'minQuantity': 'Min. Quantity',
      'category': 'Category',
      'addPart': 'Add Spare Part',
      'shiftMorning': 'Morning',
      'shiftAfternoon': 'Afternoon',
      'shiftNight': 'Night',
      'addSchedule': 'Add to Schedule',
      'notebook': 'Notebook',
      'addNote': 'Add Note',
      'editNote': 'Edit Note',
      'close': 'Close',
      'noteTitle': 'Title',
      'noteContent': 'Content',
      'noNotes': 'No notes yet. Add your first thought!',
      'failures': 'Failure Register',
      'taskList': 'Task List',
      'planning': 'Planning / Inspections',
      'settings': 'Settings',
      'pcMode': 'PC Version',
      'pcModeInfo': 'PC layout optimized for large screens',
      'productionLine': 'Production Line',
      'enterAdminPass': 'Enter admin password',
      'invalidPass': 'Invalid password',
      'selectLine': 'Select Production Line',
      'downtimeReasonFailure': 'Failure',
      'downtimeReasonPersonnel': 'Lack of Personnel',
      'downtimeReasonRawMaterial': 'Lack of Raw Material',
      'downtimeReasonChangeover': 'Changeover',
      'downtimeReasonCleaning': 'Cleaning',
      'downtimeReasonOther': 'Other',
      'addDowntime': 'Add Downtime',
      'totalDowntimeMinutes': 'Total Downtime (min)',
      'saveToRegister': 'Save to Register',
      'downtimeSaved': 'Downtime saved successfully',
      'downtimeHistory': 'Downtime Register',
      'noDowntimeData': 'No downtime data for this day',
      'shift': 'Shift',
      'barrelsWithWaterIce': 'Barrels with Water/Ice',
      'camerasCleaned': 'Vision Cameras Cleaned',
      'yes': 'Yes',
      'no': 'No',
      'next': 'Next',
      'filterByLine': 'Filter by Line',
      'filterByShift': 'Filter by Shift',
      'filterByOperator': 'Filter by Operator',
      'operator': 'Operator',
      'date': 'Date',
      'lastUpdate': 'Last update',
      'saving': 'Saving...',
      'saveInProgress': 'Save in progress, please wait...',
      'finalizeReport': 'Finalize Report',
      'finalizeReportConfirm': 'Are you sure you want to finalize and export the report? This will reset the current form.',
      'finalize': 'Finalize',
      'reportFinalized': 'Report finalized and saved to documents.',
      'selectLineAndShift': 'Please select a line and a shift to see the table',
      'drInvoerrobotVerstoord': 'Input robot malfunction (waste/broken cart)',
      'drVallendeStapels': 'Falling stacks due to bent blades',
      'drOntnesterVerstoord': 'Denester malfunction (waste/broken barrel)',
      'drWasmachineDefectAfval': 'Washing machine defect/not working (waste)',
      'drKarrentransportVerstoord': 'Cart transport malfunction (waste/broken cart)',
      'drStapelaarUitvoerrobotVerstoord': 'Stacker/output robot malfunction (waste)',
      'drFormeertafelVerstoordAfval': 'Forming table malfunction (waste/broken cart)',
      'drVisionKooiVol': 'Vision cage full',
      'drOverig': 'Other',
      'drWaterniveau': 'Water level',
      'drVastgelopenFust': 'Jammed barrel in washer',
      'drTransportbandVerstoord': 'Conveyor belt malfunction',
      'drVastloperOntnester': 'Denester jam',
      'drStapelaarVerstoordAfstelling': 'Stacker malfunction (adjustment)',
      'drUitvoerrobotVerstoord': 'Output robot malfunction',
      'drFormeertafelOmvallendeStapels': 'Forming table malfunction due to falling stacks',
      'drGeplandeReparatie': 'Planned repair/maintenance',
      'drOngeplandeReparatie': 'Unplanned repair',
      'drInvoerrobotDefect': 'Input robot defect/not working',
      'drOntnesterDefect': 'Denester defect/not working',
      'drWasmachineDefect': 'Washing machine defect/not working',
      'drKarrentransportDefect': 'Cart transport defect/not working',
      'drTransportbandDefect': 'Conveyor belt defect/not working',
      'drStapelaarDefect': 'Stacker defect/not working',
      'drFormeertafelDefect': 'Forming table defect/not working',
      'drUitvoerrobotDefect': 'Output robot defect/not working',
      'drBesturingsprobleem': 'Control problem',
      'defectiveCartsCount': 'Number of defective stack carts',
      'causes': 'Causes',
      'lock': 'Lock',
      'unlock': 'Unlock',
      'listLocked': 'List Locked',
      'storingslogInspiratie': 'storingslog(inspiratie)',
      'pollution': 'Pollution',
      'process': 'Process',
      'technology': 'Technology',
      'technicalFaults': 'Technical Faults',
      'tfInputRobotDefect': 'Input robot defect',
      'tfOntnesterDefect': 'Distributor defect',
      'tfWasmachineDefect': 'Washing machine defect',
      'tfKarrentransportDefect': 'Cart transport defect',
      'tfTransportbandDefect': 'Conveyor belt defect',
      'tfStapelaarDefect': 'Stacker defect',
      'tfFormeertafelDefect': 'Forming table defect',
      'tfUitvoerrobotDefect': 'Output robot defect',
      'tfBesturingsprobleem': 'Control problem',
      'tfLijn': 'LIJN',
      'tfFaultId': 'FAULT ID',
      'tfDateOfRegistration': 'DATE OF REGISTRATION',
      'tfPhotoOfFault': 'PHOTO OF THE FAULT',
      'tfDescriptionOfFault': 'DESCRIPTION OF THE FAULT',
      'tfLocation': 'LOCATION',
      'tfRootCause': 'ROOT CAUSE',
      'tfPriority': 'PRIORITY',
      'tfReportingPerson': 'REPORTING PERSON',
      'tfStatus': 'STATUS',
      'tfRepairStartDate': 'REPAIR START DATE',
      'tfRepairEndDate': 'REPAIR END DATE',
      'tfRepairStartTime': 'REPAIR START TIME',
      'tfRepairEndTime': 'REPAIR END TIME',
      'tfRepairedBy': 'REPAIRED BY',
      'tfDowntime': 'DOWNTIME',
      'other_category': 'Other',
      'timeLostMin': 'Time lost (min)',
      'send': 'Send',
      'finalizeStoringslog': 'Finalize Storingslog',
      'reportGenerated': 'Report generated and saved in Documents',
      'pollutionInvoerrobot': 'Invoerrobot verstoord/ collision',
      'pollutionVallendeStapels': 'Vallende stapels door kromme bledden',
      'pollutionOntnester': 'Ontnester verstoord',
      'pollutionWasmachine': 'Wasmachine verstoord',
      'pollutionStapelaar': 'Stapelaar verstoord',
      'processLijnVerstopt': 'Invoerrobot verstoord/ collision',
      'processWachtenOpOperator': 'Vallende stapels door kromme bledden',
      'processSensorVervuild': 'Ontnester verstoord',
      'processInstellingFout': 'Wasmachine verstoord',
      'processProductieStop': 'Stapelaar verstoord',
      'techPartBroken': '1. Which part of the installation broke down',
      'techFixed': '2. Has the broken part been fixed',
      'techWhoFixed': '3. Who did fix the problem',
      'techStopDuration': '4. How long did the machine stop',
      'techUploadPicture': '5. Upload a picture of the broken part for data collection',
      'faultCount': 'Fault Count',
      'totalDowntimeMinutesShort': 'Total Downtime (min)',
      'iceWater': 'Ice / Water',
      'comments': 'Comments',
      'emergencyNumbers': 'Emergency Numbers',
      'emergencyName': 'Name / Department',
      'phoneNumber': 'Phone Number',
      'emergencyCategory': 'Category (e.g. Tech, Security)',
      'addNumber': 'Add Number',
      'editNumber': 'Edit Number',
      'deleteNumber': 'Delete Number',
      'deleteNumberConfirm': 'Are you sure you want to delete this number?',
      'searchHintNumbers': 'Search by name, number...',
      'search': 'SEARCH',
      'noNumbers': 'No numbers to display',
      'noTasks': 'No tasks to display',
      'addTask': 'Add Task',
      'editTask': 'Edit Task',
      'deleteTask': 'Delete Task',
      'deleteTaskConfirm': 'Are you sure you want to delete this task?',
      'taskTitle': 'Task Title',
      'taskType': 'Task Type / Description',
      'planned': 'Planned',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'selectDateTime': 'Select execution date',
      'executionDate': 'Execution Date',
      'currentFailuresTab': 'Current Failures',
      'historyFailuresTab': 'Failure History',
      'productionListDowntime': 'Storing List Downtime',
      'planningTile': 'Planning / Inspections',
      'notebookTile': 'Notebook',
      'emergencyTile': 'Emergency Numbers',
      'productionTile': 'Storing List',
      'warehouseTile': 'Warehouse',
      'scheduleTile': 'Schedule',
      'tasksTile': 'Task List',
      'currentTasksTab': 'Current Tasks',
      'historyTasksTab': 'Task History',
      'searchMachine': 'SEARCH MACHINE',
      'searchHintAssets': 'Search by name, code or location...',
      'actions': 'ACTIONS',
      'delete': 'Delete',
      'deleteConfirm': 'Are you sure you want to delete this entry?',
      'deleteCompleteReport': 'Delete Complete Report',
      'deleteCompleteReportConfirm': 'Are you sure you want to delete the complete report for this line and shift?',
      'autoSavedShiftEnd': 'Shift ended. Report has been saved automatically.',
      'onlyCurrentShiftAllowed': 'You can only open the list for the current active shift:',
      'deleteMachine': 'Delete machine',
      'deleteNote': 'Delete note',
      'soonAvailable': 'Feature coming soon!',
      'linkPath': 'Link to documentation or path...',
      'noNotesDisplay': 'No notes to display',
      'dataSentReset': 'Data has been sent and reset.',
      'errorFinalizing': 'Error finalizing: ',
      'errorSaving': 'Error saving: ',
      'saveSuccess': 'Data saved successfully.',
      'editMachine': 'Edit machine',
      'edit': 'Edit',
      'searchHintNotes': 'Search in notes...',
      'noDataToSave': 'No data to save.',
      'entry': 'Entry',
      'newProductionEntry': 'New production entry',
      'listEmptyAddWithPlus': 'List is empty. Add entry with + button.',
      'maintenance': 'MAINTENANCE',
      'assets': 'ASSETS',
      'operations': 'OPERATIONS',
      'tools': 'TOOLS',
      'administration': 'ADMINISTRATION',
      'system': 'SYSTEM',
      'productionReportTitle': 'PRODUCTION LIST',
      'realizedProduction': 'REALIZED PRODUCTION',
      'chlorineMeasurement': 'CHLORINE MEASUREMENT',
      'endOfShiftChecklist': 'END OF SHIFT CHECKLIST',
      'commentsAndDetails': 'COMMENTS AND DETAILS',
      'barrelsEmpty': 'Waste bins empty',
      'machineClean': 'Machine clean around',
      'nozzlesPierced': 'Nozzles pierced',
      'startTime': 'Start Time',
      'endTime': 'End Time',
      'pauseDowntime': 'Pause / Downtime',
      'cartCount': 'Number of Carts',
      'totalCarts': 'Total Carts',
      'totalBarrels': 'Total Barrels',
      'chlorineLevel': 'Chlorine (Cl²)',
      'fustType': 'Barrel Type',
      'helpOperator': 'Helpoperator',
      'addName': 'Add Name',
      'addBarrelType': 'Add Barrel Type',
      'confirmAddLargeAmount': 'Are you sure you want to add 15 carts at once?',
      'confirm': 'Confirm',
      'barrelsPerCart': 'Barrels per cart',
      'doubleWashForbidden': 'Note, it is forbidden to double wash racks.',
      'manageNames': 'Manage Names',
      'editName': 'Edit Name',
      'manageBarrelTypes': 'Manage Barrel Types',
      'editBarrelType': 'Edit Barrel Type',
      'multiplier': 'Multiplier',
      'confirmDelete': 'Confirm Delete',
      'deleteConfirmMessage': 'Are you sure you want to delete',
      'listEmpty': 'List is empty',
    },
    'pl': {
      'appTitle': 'CMMS LCS CLEAN',
      'loginTitle': 'Logowanie',
      'username': 'Uzytkownik',
      'password': 'Haslo',
      'login': 'Zaloguj',
      'enterUsername': 'Podaj uzytkownika',
      'enterPassword': 'Podaj haslo',
      'machines': 'CMMS Ultimo - Maszyny',
      'addMachine': 'Dodaj maszyne',
      'cancel': 'Anuluj',
      'save': 'Zapisz',
      'name': 'Nazwa',
      'code': 'Kod',
      'location': 'Lokalizacja',
      'description': 'Opis',
      'emptyList': 'Brak maszyn. Dodaj pierwsza pozycje.',
      'dbErrorTitle': 'Wystapil blad podczas ladowania bazy.',
      'logout': 'Wyloguj',
      'theme': 'Motyw',
      'light': 'Jasny',
      'dark': 'Ciemny',
      'language': 'Jezyk',
      'requiredField': 'Pole wymagane',
      'uiScale': 'Wielkosc interfejsu',
      'loginFailed': 'Niepoprawny uzytkownik lub haslo',
      'reportFailure': 'Zglos awarie',
      'users': 'Uzytkownicy',
      'addUser': 'Dodaj uzytkownika',
      'noUsers': 'Brak uzytkownikow.',
      'admin': 'Admin',
      'userExists': 'Uzytkownik juz istnieje.',
      'permManageAssets': 'Zarzadzanie maszynami',
      'permReportFailure': 'Zglaszanie awarii',
      'permManageUsers': 'Zarzadzanie uzytkownikami',
      'manageUsers': 'Zarządzaj użytkownikami i uprawnieniami',
      'reportSaved': 'Zgloszenie zapisane lokalnie.',
      'photoPath': 'Sciezka do zdjecia (opcjonalnie)',
      'whatHappened': 'Co sie stalo?',
      'lineName': 'Linia produkcyjna',
      'resolvedQuestion': 'Czy problem zostal rozwiazany?',
      'fixDuration': 'Czas naprawy',
      'whatFixed': 'Co zostalo naprawione?',
      'whoFixed': 'Kto naprawil?',
      'quickActions': 'Szybkie akcje',
      'machinesTile': 'Aktywa / Maszyny',
      'usersTile': 'Użytkownicy',
      'reportFailureTile': 'Zgłoś awarię',
      'dashboardTitle': 'Dashboard',
      'menuTitle': 'Menu',
      'homeTitle': 'Strona główna',
      'openFailures': 'Otwarte',
      'closedFailures': 'Zamknięte',
      'totalDowntime': 'Przestój (h)',
      'efficiency': 'Wydajność',
      'failuresByLine': 'Usterki według linii',
      'topContributors': 'Liderzy zgłoszeń',
      'topFixers': 'Liderzy napraw',
      'photoStep': 'Krok 1: Dodaj zdjęcie',
      'formStep': 'Krok 2: Szczegóły awarii',
      'takePhoto': 'Zrób zdjęcie',
      'pickPhoto': 'Wybierz z galerii',
      'reason': 'Powód',
      'priority': 'Priorytet',
      'reporter': 'Osoba zgłaszająca',
      'status': 'Status',
      'open': 'OTWARTY',
      'closed': 'ZAMKNIĘTY',
      'repairStart': 'Start naprawy',
      'repairEnd': 'Koniec naprawy',
      'low': 'Niski',
      'medium': 'Średni',
      'high': 'Wysoki',
      'critical': 'Krytyczny',
      'downtime': 'Czas przestoju',
      'hours': 'godz.',
      'minutes': 'min.',
      'days': 'dni',
      'history': 'Historia usterek',
      'filterHint': 'Szukaj po ID, linii, lokalizacji...',
      'all': 'Wszystkie',
      'currentFailures': 'Bieżące usterki',
      'dateFrom': 'Data od',
      'dateTo': 'Data do',
      'downloadReport': 'Pobierz raport',
      'closeFailure': 'Zamknij usterkę',
      'yearly': 'Roczny',
      'customRange': 'Zakres dat',
      'documentation': 'Dokumentacja',
      'addDocumentation': 'Dodaj dokumentację',
      'warehouse': 'Magazyn',
      'schedule': 'Grafik',
      'productionList': 'Storing List',
      'chat': 'Czat / Kontakt',
      'onlineUsers': 'Użytkownicy online',
      'role': 'Funkcja',
      'other': 'Inne',
      'quantity': 'Ilość',
      'minQuantity': 'Ilość min.',
      'category': 'Kategoria',
      'addPart': 'Dodaj część',
      'shiftMorning': 'Rano',
      'shiftAfternoon': 'Popołudnie',
      'shiftNight': 'Noc',
      'addSchedule': 'Dodaj do grafiku',
      'notebook': 'Notatnik',
      'addNote': 'Dodaj notatkę',
      'editNote': 'Edytuj notatkę',
      'close': 'Zamknij',
      'noteTitle': 'Tytuł',
      'noteContent': 'Treść',
      'noNotes': 'Brak notatek. Dodaj swoją pierwszą myśl!',
      'failures': 'Rejestr Awarii',
      'taskList': 'Lista Zadań',
      'planning': 'Planowanie / Przeglądy',
      'settings': 'Ustawienia',
      'pcMode': 'Wersja PC',
      'productionLine': 'Linia Produkcyjna',
      'enterAdminPass': 'Podaj hasło administratora',
      'invalidPass': 'Niepoprawne hasło',
      'pcModeInfo': 'Układ PC zoptymalizowany dla dużych ekranów',
      'selectLine': 'Wybierz Linię Produkcyjną',
      'downtimeReasonFailure': 'Awaria',
      'downtimeReasonPersonnel': 'Brak personelu',
      'downtimeReasonRawMaterial': 'Brak surowca',
      'downtimeReasonChangeover': 'Przezbrojenie',
      'downtimeReasonCleaning': 'Czyszczenie',
      'downtimeReasonOther': 'Inne',
      'addDowntime': 'Dodaj przestój',
      'totalDowntimeMinutes': 'Suma przestojów (min)',
      'saveToRegister': 'Zapisz do rejestru',
      'downtimeSaved': 'Przestój zapisany pomyślnie',
      'downtimeHistory': 'Rejestr Przestojów',
      'noDowntimeData': 'Brak danych o przestojach dla tego dnia',
      'shift': 'Zmiana',
      'barrelsWithWaterIce': 'Beczki z wodą/lodem',
      'camerasCleaned': 'Kamery wizyjne wyczyszczone',
      'yes': 'Tak',
      'no': 'Nie',
      'next': 'Dalej',
      'filterByLine': 'Filtruj po Linii',
      'filterByShift': 'Filtruj po Zmianie',
      'filterByOperator': 'Filtruj po Operatorze',
      'operator': 'Operator',
      'date': 'Data',
      'lastUpdate': 'Ostatnia aktualizacja',
      'saving': 'Zapisywanie...',
      'saveInProgress': 'Trwa zapisywanie, proszę czekać...',
      'finalizeReport': 'Finalizuj raport',
      'finalizeReportConfirm': 'Czy na pewno chcesz sfinalizować i wyeksportować raport? Spowoduje to wyczyszczenie formularza.',
      'finalize': 'Finalizuj',
      'reportFinalized': 'Raport sfinalizowany i zapisany w dokumentach.',
      'selectLineAndShift': 'Proszę wybrać linię i zmianę, aby zobaczyć tabelę',
      'drInvoerrobotVerstoord': 'Zakłócenie robota wejściowego (odpady/uszkodzony wózek)',
      'drVallendeStapels': 'Upadające stosy przez wygięte łopatki',
      'drOntnesterVerstoord': 'Zakłócenie depaletyzatora (odpady/uszkodzona beczka)',
      'drWasmachineDefectAfval': 'Usterka pralki/nie działa (odpady)',
      'drKarrentransportVerstoord': 'Zakłócenie transportu wózków (odpady/uszkodzony wózek)',
      'drStapelaarUitvoerrobotVerstoord': 'Zakłócenie układarki/robota wyjściowego (odpady)',
      'drFormeertafelVerstoordAfval': 'Zakłócenie stołu formującego (odpady/uszkodzony wózek)',
      'drVisionKooiVol': 'Klatka wizyjna pełna',
      'drOverig': 'Inne',
      'drWaterniveau': 'Poziom wody',
      'drVastgelopenFust': 'Zablokowana beczka w myjce',
      'drTransportbandVerstoord': 'Zakłócenie taśmociągu',
      'drVastloperOntnester': 'Zablokowanie depaletyzatora',
      'drStapelaarVerstoordAfstelling': 'Zakłócenie układarki (regulacja)',
      'drUitvoerrobotVerstoord': 'Zakłócenie robota wyjściowego',
      'drFormeertafelOmvallendeStapels': 'Zakłócenie stołu formującego przez przewracające się stosy',
      'drGeplandeReparatie': 'Planowana naprawa/konserwacja',
      'drOngeplandeReparatie': 'Nieplanowana naprawa',
      'drInvoerrobotDefect': 'Usterka robota wejściowego/nie działa',
      'drOntnesterDefect': 'Usterka depaletyzatora/nie działa',
      'drWasmachineDefect': 'Usterka pralki/nie działa',
      'drKarrentransportDefect': 'Usterka transportu wózków/nie działa',
      'drTransportbandDefect': 'Usterka taśmociągu/nie działa',
      'drStapelaarDefect': 'Usterka układarki/nie działa',
      'drFormeertafelDefect': 'Usterka stołu formującego/nie działa',
      'drUitvoerrobotDefect': 'Usterka robota wyjściowego/nie działa',
      'drBesturingsprobleem': 'Problem ze sterowaniem',
      'defectiveCartsCount': 'Liczba uszkodzonych wózków stosujących',
      'causes': 'Przyczyny',
      'lock': 'Zablokuj',
      'unlock': 'Odblokuj',
      'listLocked': 'Lista zablokowana',
      'storingslogInspiratie': 'storingslog(inspiratie)',
      'pollution': 'Zanieczyszczenie',
      'process': 'Proces',
      'technology': 'Technologia',
      'technicalFaults': 'Usterki techniczne',
      'tfInputRobotDefect': 'Usterka robota wejściowego',
      'tfOntnesterDefect': 'Usterka dystrybutora',
      'tfWasmachineDefect': 'Usterka pralki',
      'tfKarrentransportDefect': 'Usterka transportu wózków',
      'tfTransportbandDefect': 'Usterka taśmociągu',
      'tfStapelaarDefect': 'Usterka układarki',
      'tfFormeertafelDefect': 'Usterka stołu formującego',
      'tfUitvoerrobotDefect': 'Usterka robota wyjściowego',
      'tfBesturingsprobleem': 'Problem ze sterowaniem',
      'tfLijn': 'LINIA',
      'tfFaultId': 'NR AWARII',
      'tfDateOfRegistration': 'DATA REJESTRACJI',
      'tfPhotoOfFault': 'ZDJĘCIE AWARII',
      'tfDescriptionOfFault': 'OPIS AWARII',
      'tfLocation': 'LOKALIZACJA',
      'tfRootCause': 'PRZYCZYNA',
      'tfPriority': 'PRIORYTET',
      'tfReportingPerson': 'ZGŁASZAJĄCY',
      'tfStatus': 'STATUS',
      'tfRepairStartDate': 'DATA ROZP. NAPRAWY',
      'tfRepairEndDate': 'DATA ZAK. NAPRAWY',
      'tfRepairStartTime': 'CZAS ROZP. NAPRAWY',
      'tfRepairEndTime': 'CZAS ZAK. NAPRAWY',
      'tfRepairedBy': 'NAPRAWIONE PRZEZ',
      'tfDowntime': 'PRZESTÓJ',
      'other_category': 'Inne',
      'timeLostMin': 'Stracony czas (min)',
      'send': 'Wyślij',
      'finalizeStoringslog': 'Finalizuj Storingslog',
      'reportGenerated': 'Raport został wygenerowany i zapisany w Dokumentach',
      'pollutionInvoerrobot': 'Invoerrobot verstoord/ collision',
      'pollutionVallendeStapels': 'Vallende stapels door kromme bledden',
      'pollutionOntnester': 'Ontnester verstoord',
      'pollutionWasmachine': 'Wasmachine verstoord',
      'pollutionStapelaar': 'Stapelaar verstoord',
      'processLijnVerstopt': 'Invoerrobot verstoord/ collision',
      'processWachtenOpOperator': 'Vallende stapels door kromme bledden',
      'processSensorVervuild': 'Ontnester verstoord',
      'processInstellingFout': 'Wasmachine verstoord',
      'processProductieStop': 'Stapelaar verstoord',
      'techPartBroken': '1. Która część instalacji uległa awarii',
      'techFixed': '2. Czy uszkodzona część została naprawiona',
      'techWhoFixed': '3. Kto naprawił problem',
      'techStopDuration': '4. Jak długo maszyna była zatrzymana',
      'techUploadPicture': '5. Prześlij zdjęcie uszkodzonej części do celów gromadzenia danych',
      'faultCount': 'Liczba usterek',
      'totalDowntimeMinutesShort': 'Suma przestojów (min)',
      'iceWater': 'Lód / Woda',
      'comments': 'Komentarze',
      'emergencyNumbers': 'Numery Alarmowe',
      'emergencyName': 'Nazwa / Dział',
      'phoneNumber': 'Numer Telefonu',
      'emergencyCategory': 'Kategoria (np. Tech, Ochrona)',
      'addNumber': 'Dodaj Numer',
      'editNumber': 'Edytuj Numer',
      'deleteNumber': 'Usuń Numer',
      'deleteNumberConfirm': 'Czy na pewno chcesz usunąć ten numer?',
      'searchHintNumbers': 'Szukaj po nazwie, numerze...',
      'search': 'SZUKAJ',
      'noNumbers': 'Brak numerów do wyświetlenia',
      'noTasks': 'Brak zadań do wyświetlenia',
      'addTask': 'Dodaj Zadanie',
      'editTask': 'Edytuj Zadanie',
      'deleteTask': 'Usuń Zadanie',
      'deleteTaskConfirm': 'Czy na pewno chcesz usunąć to zadanie?',
      'taskTitle': 'Tytuł Zadania',
      'taskType': 'Typ Zadania / Opis',
      'planned': 'Zaplanowane',
      'completed': 'Zrealizowane',
      'cancelled': 'Anulowane',
      'selectDateTime': 'Wybierz datę realizacji',
      'executionDate': 'Data realizacji',
      'currentFailuresTab': 'Bieżące usterki',
      'historyFailuresTab': 'Historia usterek',
      'productionListDowntime': 'Przestój ze Storing List',
      'planningTile': 'Planowanie / Przeglądy',
      'notebookTile': 'Notatnik',
      'emergencyTile': 'Numery Alarmowe',
      'productionTile': 'Storing List',
      'warehouseTile': 'Magazyn',
      'scheduleTile': 'Grafik',
      'tasksTile': 'Lista Zadań',
      'currentTasksTab': 'Bieżące zadania',
      'historyTasksTab': 'Historia zadań',
      'searchMachine': 'SZUKAJ MASZYNY',
      'searchHintAssets': 'Wyszukaj po nazwie, kodzie lub lokalizacji...',
      'actions': 'AKCJE',
      'delete': 'Usuń',
      'deleteConfirm': 'Czy na pewno chcesz usunąć ten wpis?',
      'deleteCompleteReport': 'Usuń kompletny raport',
      'deleteCompleteReportConfirm': 'Czy na pewno chcesz usunąć cały raport dla tej linii i zmiany?',
      'autoSavedShiftEnd': 'Koniec zmiany. Raport został zapisany automatycznie.',
      'onlyCurrentShiftAllowed': 'Możesz otworzyć listę tylko dla obecnie trwającej zmiany:',
      'deleteMachine': 'Usuń maszynę',
      'deleteNote': 'Usuń notatkę',
      'soonAvailable': 'Funkcja wkrótce dostępna!',
      'linkPath': 'Link do dokumentacji lub ścieżka...',
      'noNotesDisplay': 'Brak notatek do wyświetlenia',
      'dataSentReset': 'Dane zostały przesłane i zresetowane.',
      'errorFinalizing': 'Błąd podczas finalizacji: ',
      'errorSaving': 'Błąd zapisu: ',
      'saveSuccess': 'Zapisano pomyślnie.',
      'editMachine': 'Edytuj maszynę',
      'edit': 'Edytuj',
      'searchHintNotes': 'Szukaj w notatkach...',
      'noDataToSave': 'Brak danych do zapisania.',
      'entry': 'Wpis',
      'newProductionEntry': 'Nowy wpis produkcyjny',
      'listEmptyAddWithPlus': 'Lista jest pusta. Dodaj wpis przyciskiem +.',
      'maintenance': 'UTRZYMANIE RUCHU',
      'assets': 'ZASOBY',
      'operations': 'OPERACJE',
      'tools': 'NARZĘDZIA',
      'administration': 'ADMINISTRACJA',
      'system': 'SYSTEM',
      'productionReportTitle': 'PRODUCTION LIST',
      'realizedProduction': 'ZREALIZOWANA PRODUKCJA',
      'chlorineMeasurement': 'POMIAR CHLORU',
      'endOfShiftChecklist': 'LISTA KONTROLNA KONIEC ZMIANY',
      'commentsAndDetails': 'UWAGI I SZCZEGÓŁY',
      'barrelsEmpty': 'Puste kosze na śmieci',
      'machineClean': 'Maszyna czysta wokół',
      'nozzlesPierced': 'Dysze przebite',
      'startTime': 'Czas rozpoczęcia',
      'endTime': 'Czas zakończenia',
      'pauseDowntime': 'Pauza / Przestój',
      'cartCount': 'Liczba wózków',
      'totalCarts': 'Suma wózków',
      'totalBarrels': 'Suma beczek',
      'chlorineLevel': 'Chlor (Cl²)',
      'fustType': 'Typ beczki',
      'helpOperator': 'Pomocnik operatora',
      'addName': 'Dodaj imię',
      'addBarrelType': 'Dodaj typ beczki',
      'confirmAddLargeAmount': 'Czy na pewno chcesz dodać 15 wózków naraz?',
      'confirm': 'Potwierdź',
      'barrelsPerCart': 'Liczba beczek na wózek',
      'doubleWashForbidden': 'Uwaga, zabrania się podwójnego mycia regałów.',
      'manageNames': 'Zarządzaj listą osób',
      'editName': 'Edytuj imię',
      'manageBarrelTypes': 'Zarządzaj typami beczek',
      'editBarrelType': 'Edytuj typ beczki',
      'multiplier': 'Mnożnik',
      'confirmDelete': 'Potwierdź usunięcie',
      'deleteConfirmMessage': 'Czy na pewno chcesz usunąć',
      'listEmpty': 'Lista jest pusta',
    },
    'nl': {
      'appTitle': 'CMMS LCS CLEAN',
      'loginTitle': 'Inloggen',
      'username': 'Gebruiker',
      'password': 'Wachtwoord',
      'login': 'Inloggen',
      'enterUsername': 'Voer gebruiker in',
      'enterPassword': 'Voer wachtwoord in',
      'machines': 'CMMS Ultimo - Machines',
      'addMachine': 'Machine toevoegen',
      'cancel': 'Annuleren',
      'save': 'Opslaan',
      'name': 'Naam',
      'code': 'Code',
      'location': 'Locatie',
      'description': 'Beschrijving',
      'emptyList': 'Nog geen machines. Voeg de eerste toe.',
      'dbErrorTitle': 'Fout bij laden van database.',
      'logout': 'Uitloggen',
      'theme': 'Thema',
      'light': 'Licht',
      'dark': 'Donker',
      'language': 'Taal',
      'requiredField': 'Verplicht veld',
      'uiScale': 'Interfacegrootte',
      'loginFailed': 'Ongeldige gebruiker of wachtwoord',
      'reportFailure': 'Storing melden',
      'users': 'Gebruikers',
      'addUser': 'Gebruiker toevoegen',
      'noUsers': 'Nog geen gebruikers.',
      'admin': 'Admin',
      'userExists': 'Gebruiker bestaat al.',
      'permManageAssets': 'Machines beheren',
      'permReportFailure': 'Storingen melden',
      'permManageUsers': 'Gebruikers beheren',
      'reportSaved': 'Melding lokaal opgeslagen.',
      'photoPath': 'Fotopad (optioneel)',
      'whatHappened': 'Wat is er gebeurd?',
      'lineName': 'Productielijn',
      'resolvedQuestion': 'Is het probleem opgelost?',
      'fixDuration': 'Hersteltijd',
      'whatFixed': 'Wat is gerepareerd?',
      'whoFixed': 'Wie heeft het gerepareerd?',
      'quickActions': 'Snelle acties',
      'machinesTile': 'Activa / Machines',
      'usersTile': 'Gebruikers',
      'reportFailureTile': 'Storing melden',
      'dashboardTitle': 'Dashboard',
      'failures': 'Storingsregister',
      'history': 'Geschiedenis',
      'currentFailures': 'Huidige storingen',
      'notebook': 'Notitieblok',
      'addNote': 'Notitie toevoegen',
      'editNote': 'Notitie bewerken',
      'close': 'Sluiten',
      'warehouse': 'Magazijn',
      'schedule': 'Rooster',
      'productionList': 'Storing List',
      'storingslogInspiratie': 'storingslog(inspiratie)',
      'pollution': 'Vervuiling',
      'process': 'Proces',
      'technology': 'Techniek',
      'technicalFaults': 'Technische fouten',
      'tfInputRobotDefect': 'Invoerrobot defect',
      'tfOntnesterDefect': 'Ontnester defect',
      'tfWasmachineDefect': 'Wasmachine defect',
      'tfKarrentransportDefect': 'Karrentransport defect',
      'tfTransportbandDefect': 'Transportband defect',
      'tfStapelaarDefect': 'Stapelaar defect',
      'tfFormeertafelDefect': 'Formeertafel defect',
      'tfUitvoerrobotDefect': 'Uitvoerrobot defect',
      'tfBesturingsprobleem': 'Besturingsprobleem',
      'other_category': 'Overig',
      'timeLostMin': 'Tijd verloren (min)',
      'send': 'Send',
      'finalizeStoringslog': 'Storingslog Afronden',
      'reportGenerated': 'Rapport gegenereerd en opgeslagen w Documenten',
      'pollutionInvoerrobot': 'Invoerrobot verstoord/ collision',
      'pollutionVallendeStapels': 'Vallende stapels door kromme bleden',
      'pollutionOntnester': 'Ontnester verstoord',
      'pollutionWasmachine': 'Wasmachine verstoord',
      'pollutionStapelaar': 'Stapelaar verstoord',
      'processLijnVerstopt': 'Lijn verstopt/geblokkeerd',
      'processWachtenOpOperator': 'Wachten op operator',
      'processSensorVervuild': 'Sensor vervuild/belemmerd',
      'processInstellingFout': 'Instelling fout/parameter',
      'processProductieStop': 'Productiestop (algemeen)',
      'techPartBroken': '1. Welk deel van de installatie is defect geraakt',
      'techFixed': '2. Is het defecte onderdeel gerepareerd',
      'techWhoFixed': '3. Wie heeft het probleem opgelost',
      'techStopDuration': '4. Hoe lang stond de machine stil',
      'techUploadPicture': '5. Upload een foto van het defecte onderdeel voor gegevensverzameling',
      'taskList': 'Takenlijst',
      'planning': 'Planning / Inspecties',
      'settings': 'Instellingen',
      'operator': 'Operator',
      'date': 'Datum',
      'lastUpdate': 'Laatste update',
      'saving': 'Opslaan...',
      'saveInProgress': 'Bezig z met opslaan, even geduld...',
      'finalizeReport': 'Rapport afronden',
      'finalizeReportConfirm': 'Weet u zeker dat u het raport wilt afronden en exporteren? Dit zal het huidige formulier resetten.',
      'finalize': 'Afronden',
      'selectLineAndShift': 'Selecteer een lijn en een shift om de tabel te zien',
      'drInvoerrobotVerstoord': 'Invoerrobot verstoord (afval/kapotte kar)',
      'drVallendeStapels': 'Vallende stapels door kromme bledden',
      'drOntnesterVerstoord': 'Ontnester verstoord (afval/kapot fust)',
      'drWasmachineDefectAfval': 'Wasmachine defect/werkt niet (afval)',
      'drKarrentransportVerstoord': 'Karrentransport verstoord (afval/kapotte kar)',
      'drStapelaarUitvoerrobotVerstoord': 'Stapelaar/uitvoerrobot verstoord (afval)',
      'drFormeertafelVerstoordAfval': 'Formeertafel verstoord (afval/kapotte kar)',
      'drVisionKooiVol': 'Vision kooi vol',
      'drOverig': 'Overig',
      'drWaterniveau': 'Waterniveau',
      'drVastgelopenFust': 'Vastgelopen fust in wasser',
      'drTransportbandVerstoord': 'Transportband verstoord',
      'drVastloperOntnester': 'Vastloper ontnester',
      'drStapelaarVerstoordAfstelling': 'Stapelaar verstoord (afstelling)',
      'drUitvoerrobotVerstoord': 'Uitvoerrobot verstoord',
      'drFormeertafelOmvallendeStapels': 'Formeertafel verstoord przez omvallende stapels',
      'drGeplandeReparatie': 'Geplande reparatie/onderhoud',
      'drOngeplandeReparatie': 'Ongeplande reparatie',
      'drInvoerrobotDefect': 'Invoerrobot defect/werkt niet',
      'drOntnesterDefect': 'Ontnester defect/werkt niet',
      'drWasmachineDefect': 'Wasmachine defect/werkt niet',
      'drKarrentransportDefect': 'Karrentransport defect/werkt niet',
      'drTransportbandDefect': 'Transportband defect/werkt niet',
      'drStapelaarDefect': 'Stapelaar defect/werkt niet',
      'drFormeertafelDefect': 'Formeertafel defect/werkt niet',
      'drUitvoerrobotDefect': 'Uitvoerrobot defect/werkt niet',
      'drBesturingsprobleem': 'Besturingsprobleem',
      'defectiveCartsCount': 'Aantal defecte stapelwagens',
      'causes': 'Oorzaken',
      'lock': 'Vergrendelen',
      'unlock': 'Ontgrendelen',
      'listLocked': 'Lijst vergrendeld',
      'faultCount': 'Aantal storingen',
      'totalDowntimeMinutesShort': 'Totaal uitval (min)',
      'iceWater': 'IJS / Water',
      'comments': 'Opmerkingen',
      'emergencyNumbers': 'Noodnummers',
      'emergencyName': 'Naam / Afdeling',
      'phoneNumber': 'Telefoonnummer',
      'emergencyCategory': 'Categorie (bijv. Tech, Beveiliging)',
      'addNumber': 'Nummer toevoegen',
      'editNumber': 'Nummer bewerken',
      'deleteNumber': 'Nummer verwijderen',
      'deleteNumberConfirm': 'Weet u zeker dat u dit nummer wilt verwijderen?',
      'searchHintNumbers': 'Zoek op naam, nummer...',
      'search': 'ZOEKEN',
      'noNumbers': 'Geen nummers om weer te geven',
      'noTasks': 'Geen taken om weer te geven',
      'addTask': 'Taak toevoegen',
      'editTask': 'Taak bewerken',
      'deleteTask': 'Taak verwijderen',
      'deleteTaskConfirm': 'Weet u zeker dat u deze taak wilt verwijderen?',
      'taskTitle': 'Taak titel',
      'taskType': 'Taak type / Beschrijving',
      'currentFailuresTab': 'Huidige storingen',
      'historyFailuresTab': 'Storingsgeschiedenis',
      'productionListDowntime': 'Productielijst uitval',
      'planningTile': 'Planning / Inspecties',
      'notebookTile': 'Notitieblok',
      'emergencyTile': 'Noodnummers',
      'productionTile': 'Storing List',
      'warehouseTile': 'Magazijn',
      'scheduleTile': 'Rooster',
      'tasksTile': 'Takenlijst',
      'searchMachine': 'ZOEK MACHINE',
      'searchHintAssets': 'Zoek op naam, code of locatie...',
      'actions': 'ACTIES',
      'currentTasksTab': 'Huidige taken',
      'historyTasksTab': 'Takenoverzicht',
      'delete': 'Verwijderen',
      'deleteConfirm': 'Weet u zeker dat u dit item wilt verwijderen?',
      'deleteMachine': 'Machine verwijderen',
      'deleteNote': 'Notitie verwijderen',
      'soonAvailable': 'Binnenkort beschikbaar!',
      'linkPath': 'Link naar documentatie of pad...',
      'noNotesDisplay': 'Geen notities om weer te geven',
      'dataSentReset': 'Gegevens zijn verzonden en gereset.',
      'errorFinalizing': 'Fout bij afronden: ',
      'errorSaving': 'Fout bij opslaan: ',
      'saveSuccess': 'Gegevens succesvol opgeslagen.',
      'editMachine': 'Machine bewerken',
      'edit': 'Bewerken',
      'searchHintNotes': 'Zoeken in notities...',
      'noDataToSave': 'Geen gegevens om op te slaan.',
      'entry': 'Invoer',
      'newProductionEntry': 'Nieuwe productie-invoer',
      'listEmptyAddWithPlus': 'Lijst is leeg. Voeg invoer toe met de + knop.',
      'doubleWashForbidden': 'Let op, het is verboden rekken dubbel te wassen.',
      'manageNames': 'Namen beheren',
      'editName': 'Naam bewerken',
      'manageBarrelTypes': 'Vat-types beheren',
      'editBarrelType': 'Vat-type bewerken',
      'multiplier': 'Vermenigvuldiger',
      'confirmDelete': 'Verwijdering bevestigen',
      'deleteConfirmMessage': 'Weet u zeker dat u wilt verwijderen',
      'listEmpty': 'Lijst jest pusta',
    },
    'tr': {
      'appTitle': 'CMMS LCS CLEAN',
      'loginTitle': 'Giris',
      'username': 'Kullanici',
      'password': 'Sifre',
      'login': 'Giris',
      'enterUsername': 'Kullanici girin',
      'enterPassword': 'Sifre girin',
      'machines': 'CMMS Ultimo - Makineler',
      'addMachine': 'Makine ekle',
      'cancel': 'Iptal',
      'save': 'Kaydet',
      'name': 'Ad',
      'code': 'Kod',
      'location': 'Konum',
      'description': 'Aciklama',
      'emptyList': 'Henuz makine yok. Ilk kaydi ekleyin.',
      'dbErrorTitle': 'Veritabani yukleme hatasi.',
      'logout': 'Cikis',
      'theme': 'Tema',
      'light': 'Acik',
      'dark': 'Koyu',
      'language': 'Dil',
      'requiredField': 'Zorunlu alan',
      'uiScale': 'Arayuz boyutu',
      'loginFailed': 'Gecersiz kullanici veya sifre',
      'reportFailure': 'Ariza bildir',
      'users': 'Kullanicilar',
      'addUser': 'Kullanici ekle',
      'noUsers': 'Henuz kullanici yok.',
      'admin': 'Admin',
      'userExists': 'Kullanici zaten var.',
      'permManageAssets': 'Makine yonetimi',
      'permReportFailure': 'Ariza bildirme',
      'permManageUsers': 'Kullanici yonetimi',
      'reportSaved': 'Kayit yerel olarak kaydedildi.',
      'photoPath': 'Fotograf yolu (opsiyonel)',
      'whatHappened': 'Ne oldu?',
      'lineName': 'Uretim hatti',
      'resolvedQuestion': 'Sorun cozuldu mu?',
      'fixDuration': 'Onarim suresi',
      'whatFixed': 'Ne onarildi?',
      'whoFixed': 'Kim onardi?',
      'quickActions': 'Hızlı işlemler',
      'machinesTile': 'Varlıklar / Makineler',
      'usersTile': 'Kullanıcılar',
      'reportFailureTile': 'Arıza Bildir',
      'dashboardTitle': 'Dashboard',
      'failures': 'Arıza Kaydı',
      'history': 'Geçmiş',
      'currentFailures': 'Mevcut Arızalar',
      'notebook': 'Not Defteri',
      'addNote': 'Not Ekle',
      'editNote': 'Notu Düzenle',
      'close': 'Kapat',
      'warehouse': 'Depo',
      'schedule': 'Program',
      'productionList': 'Storing List',
      'taskList': 'Görev Listesi',
      'planning': 'Planlama / Denetimler',
      'alerts': 'Bildirimler / Uyarılar',
      'emergencyNumbers': 'Acil Durum Numaraları',
      'costs': 'Maliyetler / Bütçe',
      'settings': 'Ayarlar',
      'technicalFaults': 'Teknik Arızalar',
      'tfInputRobotDefect': 'Giriş robotu arızası',
      'tfOntnesterDefect': 'Distribütör arızası',
      'tfWasmachineDefect': 'Yıkama makinesi arızası',
      'tfKarrentransportDefect': 'Araba taşıma arızası',
      'tfTransportbandDefect': 'Konveyör bant arızası',
      'tfStapelaarDefect': 'İstifleyici arızası',
      'tfFormeertafelDefect': 'Şekillendirme masası arızası',
      'tfUitvoerrobotDefect': 'Çıkış robotu arızası',
      'tfBesturingsprobleem': 'Kontrol problemi',
      'faultCount': 'Arıza Sayısı',
      'iceWater': 'Buz / Su',
      'emergencyName': 'Ad / Departman',
      'phoneNumber': 'Telefon Numarası',
      'emergencyCategory': 'Kategori (örn. Teknoloji, Güvenlik)',
      'addNumber': 'Numara Ekle',
      'editNumber': 'Numara Düzenle',
      'deleteNumber': 'Numara Sil',
      'deleteNumberConfirm': 'Bu numarayı silmek istediğinizden emin misiniz?',
      'searchHintNumbers': 'Ad, numara ile ara...',
      'search': 'ARAMA',
      'noNumbers': 'Görüntülenecek numara yok',
      'noTasks': 'Görüntülenecek görev yok',
      'addTask': 'Görev Ekle',
      'editTask': 'Görev Düzenle',
      'deleteTask': 'Görev Sil',
      'deleteTaskConfirm': 'Bu görevi silmek istediğinizden emin misiniz?',
      'taskTitle': 'Görev Başlığı',
      'taskType': 'Görev Türü / Açıklama',
      'currentFailuresTab': 'Mevcut Arızalar',
      'historyFailuresTab': 'Arıza Geçmişi',
      'productionListDowntime': 'Üretim Listesi Kesintisi',
      'planningTile': 'Planlama / Denetimler',
      'notebookTile': 'Not Defteri',
      'emergencyTile': 'Acil Durum Numaraları',
      'productionTile': 'Storing List',
      'warehouseTile': 'Depo',
      'scheduleTile': 'Program',
      'tasksTile': 'Görev Listesi',
      'searchMachine': 'MAKİNE ARA',
      'searchHintAssets': 'Ad, kod veya konuma göre ara...',
      'actions': 'İŞLEMLER',
      'currentTasksTab': 'Mevcut Görevler',
      'historyTasksTab': 'Görev Geçmişi',
      'delete': 'Sil',
      'deleteConfirm': 'Bu öğeyi silmek istediğinizden emin misiniz?',
      'deleteMachine': 'Makineyi sil',
      'deleteNote': 'Notu sil',
      'soonAvailable': 'Özellik yakında gelecek!',
      'linkPath': 'Dokümantasyon bağlantısı veya yol...',
      'noNotesDisplay': 'Görüntülenecek not yok',
      'dataSentReset': 'Veriler gönderildi ve sıfırlandı.',
      'errorFinalizing': 'Sonlandırma hatası: ',
      'errorSaving': 'Kaydetme hatası: ',
      'saveSuccess': 'Veriler başarıyla kaydedildi.',
      'editMachine': 'Makineyi düzenle',
      'edit': 'Düzenle',
      'searchHintNotes': 'Notlarda ara...',
      'noDataToSave': 'Kaydedilecek veri yok.',
      'entry': 'Giriş',
      'newProductionEntry': 'Yeni üretim girişi',
      'listEmptyAddWithPlus': 'Liste boş. + butonu ile giriş ekleyin.',
      'date': 'Tarih',
      'productionReportTitle': 'Storing List',
      'realizedProduction': 'Gerçekleşen Üretim',
      'chlorineMeasurement': 'Klor Ölçümü',
      'endOfShiftChecklist': 'Vardiya Sonu Kontrol Listesi',
      'commentsAndDetails': 'Yorumlar ve Detaylar',
      'barrelsEmpty': 'Atık kutuları boş',
      'machineClean': 'Makine çevresi temiz',
      'nozzlesPierced': 'Nozullar delindi',
      'startTime': 'Başlangıç Zamanı',
      'endTime': 'Bitiş Zamanı',
      'pauseDowntime': 'Duraklama / Kesinti',
      'cartCount': 'Araba Sayısı',
      'totalCarts': 'Toplam Araba',
      'totalBarrels': 'Toplam Varil',
      'chlorineLevel': 'Klor (Cl²)',
      'fustType': 'Varil Tipi',
      'helpOperator': 'Yardımcı Operatör',
      'addName': 'İsim Ekle',
      'addBarrelType': 'Varil Tipi Ekle',
      'confirmAddLargeAmount': 'Aynı anda 15 araba eklemek istediğinizden emin misiniz?',
      'confirm': 'Onayla',
      'barrelsPerCart': 'Araba başına varil',
      'doubleWashForbidden': 'Dikkat, rafların çift yıkanması yasaktır.',
      'manageNames': 'İsimleri Yönet',
      'editName': 'İsmi Düzenle',
      'manageBarrelTypes': 'Varil Tiplerini Yönet',
      'editBarrelType': 'Varil Tipini Düzenle',
      'multiplier': 'Çarpan',
      'confirmDelete': 'Silmeyi Onayla',
      'deleteConfirmMessage': 'Silmek istediğinizden emin misiniz?',
      'listEmpty': 'Liste boş',
    },
    'bg': {
      'appTitle': 'CMMS LCS CLEAN',
      'loginTitle': 'Vhod',
      'username': 'Potrebitel',
      'password': 'Parola',
      'login': 'Vlez',
      'enterUsername': 'Vavedi potrebitel',
      'enterPassword': 'Vavedi parola',
      'machines': 'CMMS Ultimo - Mashini',
      'addMachine': 'Dobavi mashina',
      'cancel': 'Otmeni',
      'save': 'Zapis',
      'name': 'Ime',
      'code': 'Kod',
      'location': 'Lokaciya',
      'description': 'Opisanie',
      'emptyList': 'Nyama mashini. Dobavi parvata.',
      'dbErrorTitle': 'Greshka pri zarejdane na bazata.',
      'logout': 'Izhod',
      'theme': 'Tema',
      'light': 'Svetal',
      'dark': 'Tamna',
      'language': 'Ezik',
      'requiredField': 'Zadalzhitelno pole',
      'uiScale': 'Razmer na interfazha',
      'loginFailed': 'Nevraliden potrebitel ili parola',
      'reportFailure': 'Dokladvai avariya',
      'users': 'Potrebiteli',
      'addUser': 'Dobavi potrebitel',
      'noUsers': 'Nyama potrebiteli.',
      'admin': 'Admin',
      'userExists': 'Potrebitelyat veche sushtestvuva.',
      'permManageAssets': 'Upravlenie na mashini',
      'permReportFailure': 'Dokladvane na avarii',
      'permManageUsers': 'Upravlenie na potrebiteli',
      'reportSaved': 'Dokladat e zapazen lokalno.',
      'photoPath': 'Pat do snimka (po izbor)',
      'whatHappened': 'Kakvo se sluchi?',
      'lineName': 'Proizvodstvena liniya',
      'resolvedQuestion': 'Problemat reshen li e?',
      'fixDuration': 'Vreme za remont',
      'whatFixed': 'Kakvo e popraveno?',
      'whoFixed': 'Koy go popravi?',
      'quickActions': 'Бързи действия',
      'machinesTile': 'Активи / Машини',
      'usersTile': 'Потребители',
      'reportFailureTile': 'Докладвай авария',
      'dashboardTitle': 'Dashboard',
      'failures': 'Регистър на авариите',
      'notebook': 'Бележник',
      'addNote': 'Добави бележка',
      'editNote': 'Редактирай бележка',
      'close': 'Затвори',
      'warehouse': 'Склад',
      'schedule': 'График',
      'productionList': 'Storing List',
      'taskList': 'Списък със задачи',
      'planning': 'Планиране / Инспекции',
      'settings': 'Настройки',
      'technicalFaults': 'Технически неизправности',
      'tfInputRobotDefect': 'Дефект на входящия robot',
      'tfOntnesterDefect': 'Дефект на дистрибутора',
      'tfWasmachineDefect': 'Дефект на пералната машина',
      'tfKarrentransportDefect': 'Дефект на транспорта на колички',
      'tfTransportbandDefect': 'Дефект на транспортната лента',
      'tfStapelaarDefect': 'Дефект на стакера',
      'tfFormeertafelDefect': 'Дефект на формиращата маса',
      'tfUitvoerrobotDefect': 'Дефект на изходящия робот',
      'tfBesturingsprobleem': 'Проблем с управлението',
      'faultCount': 'Брой неизправности',
      'iceWater': 'Лед / Вода',
      'emergencyNumbers': 'Спешни номера',
      'emergencyName': 'Име / Отдел',
      'phoneNumber': 'Телефонен номер',
      'emergencyCategory': 'Категория (напр. Техническа, Охрана)',
      'addNumber': 'Добави номер',
      'editNumber': 'Редактирай номер',
      'deleteNumber': 'Изтрий номер',
      'deleteNumberConfirm': 'Сигурни ли сте, че искате да изтриете този номер?',
      'searchHintNumbers': 'Търсене по име, номер...',
      'search': 'ТЪРСЕНЕ',
      'noNumbers': 'Няма номера за показване',
      'noTasks': 'Няма задачи за показване',
      'addTask': 'Добави задача',
      'editTask': 'Редактирай задача',
      'deleteTask': 'Изтрий задача',
      'deleteTaskConfirm': 'Сигурни ли сте, че искате да изтриете тази задача?',
      'taskTitle': 'Заглавие на задачата',
      'taskType': 'Тип на задачата / Описание',
      'currentFailuresTab': 'Текущи повреди',
      'historyFailuresTab': 'История на повредите',
      'productionListDowntime': 'Престой от производствения списък',
      'planningTile': 'Планиране / Инспекции',
      'notebookTile': 'Бележник',
      'emergencyTile': 'Спешни номера',
      'productionTile': 'Storing List',
      'warehouseTile': 'Склад',
      'scheduleTile': 'График',
      'tasksTile': 'Списък със задачи',
      'searchMachine': 'ТЪРСЕНЕ НА МАШИНА',
      'searchHintAssets': 'Търсене по име, код или локация...',
      'actions': 'ДЕЙСТВИЯ',
      'currentTasksTab': 'Текущи задачи',
      'historyTasksTab': 'История на задачите',
      'delete': 'Изтриване',
      'deleteConfirm': 'Сигурни ли сте, че искате да изтриете този елемент?',
      'deleteMachine': 'Изтриване на машина',
      'deleteNote': 'Изтриване на бележка',
      'soonAvailable': 'Функцията ще бъде налична скоро!',
      'linkPath': 'Връзка към документация или път...',
      'noNotesDisplay': 'Няма бележки за показване',
      'dataSentReset': 'Данните са изпратени и нулирани.',
      'errorFinalizing': 'Грешка при финализиране: ',
      'errorSaving': 'Грешка при запазване: ',
      'saveSuccess': 'Данните са запазени успешно.',
      'editMachine': 'Редактиране на машина',
      'edit': 'Редактиране',
      'searchHintNotes': 'Търсене в бележките...',
      'noDataToSave': 'Няма данни за запазване.',
      'entry': 'Запис',
      'newProductionEntry': 'Нов производствен запис',
      'listEmptyAddWithPlus': 'Списъкът е празен. Добавете запис с бутона +.',
      'date': 'Дата',
      'productionReportTitle': 'Storing List',
      'realizedProduction': 'Реализирано производство',
      'chlorineMeasurement': 'Измерване на хлор',
      'endOfShiftChecklist': 'Контролен списък в края на смяната',
      'commentsAndDetails': 'Коментари и подробности',
      'barrelsEmpty': 'Кофите за боклук са празни',
      'machineClean': 'Машината е чиста наоколо',
      'nozzlesPierced': 'Дюзите са пробити',
      'startTime': 'Начален час',
      'endTime': 'Краен час',
      'pauseDowntime': 'Пауза / Престой',
      'cartCount': 'Брой колички',
      'totalCarts': 'Общо колички',
      'totalBarrels': 'Общо бъчви',
      'chlorineLevel': 'Хлор (Cl²)',
      'fustType': 'Тип бъчва',
      'helpOperator': 'Помощник оператор',
      'addName': 'Добави име',
      'addBarrelType': 'Добави тип бъчва',
      'confirmAddLargeAmount': 'Сигурни ли сте, че искате да добавите 15 колички наведнъж?',
      'confirm': 'Потвърди',
      'barrelsPerCart': 'Бъчви на количка',
      'doubleWashForbidden': 'Забележка: Забранено е двойното измиване на рафтове.',
      'manageNames': 'Управлявай имената',
      'editName': 'Редактирай име',
      'manageBarrelTypes': 'Управлявай типовете бъчви',
      'editBarrelType': 'Редактирай тип бъчва',
      'multiplier': 'Множител',
      'confirmDelete': 'Потвърди изтриването',
      'deleteConfirmMessage': 'Сигурни ли сте, че искате да изтриете',
      'listEmpty': 'Списъкът е празен',
    },
    'el': {
      'appTitle': 'CMMS LCS CLEAN',
      'loginTitle': 'Syndesi',
      'username': 'Xristis',
      'password': 'Kodikos',
      'login': 'Eisodos',
      'enterUsername': 'Sympliroste xristi',
      'enterPassword': 'Sympliroste kodiko',
      'machines': 'CMMS Ultimo - Mixanes',
      'addMachine': 'Prosthiki mixanis',
      'cancel': 'Akyrwsi',
      'save': 'Apothikefsi',
      'name': 'Onoma',
      'code': 'Kodikos',
      'location': 'Topothesia',
      'description': 'Perigrafi',
      'emptyList': 'Den yparxoun mixanes. Prostheste tin proti.',
      'dbErrorTitle': 'Sfalma fortosis vasis dedomenon.',
      'logout': 'Aposyndesi',
      'theme': 'Thema',
      'light': 'Foteino',
      'dark': 'Skoteino',
      'language': 'Glossa',
      'requiredField': 'Ypoxreotiko pedio',
      'uiScale': 'Melethos dieropikis',
      'loginFailed': 'Lathos xristis i kodikos',
      'reportFailure': 'Dilosi vlavis',
      'users': 'Xristes',
      'addUser': 'Prosthiki xristi',
      'noUsers': 'Den yparxoun xristes.',
      'admin': 'Admin',
      'userExists': 'O xristis yparxei idi.',
      'permManageAssets': 'Diaxeirisi mixanon',
      'permReportFailure': 'Dilosi vlavon',
      'permManageUsers': 'Diaxeirisi xriston',
      'reportSaved': 'I dilosi apothikeftike topika.',
      'technicalFaults': 'Τεχνικές Βλάβες',
      'tfInputRobotDefect': 'Βλάβη ρομπότ εισόδου',
      'tfOntnesterDefect': 'Βλάβη διανομέα',
      'tfWasmachineDefect': 'Βλάβη πλυντηρίου',
      'tfKarrentransportDefect': 'Βλάβη μεταφοράς καροτσιών',
      'tfTransportbandDefect': 'Βλάβη μεταφορικής ταινίας',
      'tfStapelaarDefect': 'Βλάβη στοιβακτή',
      'tfFormeertafelDefect': 'Βλάβη τραπεζιού διαμόρφωσης',
      'tfUitvoerrobotDefect': 'Βλάβη ρομπότ εξόδου',
      'tfBesturingsprobleem': 'Πρόβλημα ελέγχου',
      'photoPath': 'Monopati fotografias (proairetika)',
      'whatHappened': 'Ti synedvi?',
      'lineName': 'Grammi paragogis',
      'resolvedQuestion': 'Lythike to provlima?',
      'fixDuration': 'Diarkeia episkevis',
      'whatFixed': 'Ti epidiorthothike?',
      'whoFixed': 'Poios to epidiorthose?',
      'quickActions': 'Γρήγορες ενέργειες',
      'machinesTile': 'Πάγια / Μηχανές',
      'usersTile': 'Χρήστες',
      'reportFailureTile': 'Δήλωση βλάβης',
      'dashboardTitle': 'Dashboard',
      'failures': 'Μητρώο βλαβών',
      'notebook': 'Σημειωματάριο',
      'addNote': 'Προσθήκη σημείωσης',
      'editNote': 'Επεξεργασία σημείωσης',
      'close': 'Κλείσιμο',
      'warehouse': 'Αποθήκη',
      'schedule': 'Πρόγραμμα',
      'productionList': 'Storing List',
      'taskList': 'Λίστα εργασιών',
      'planning': 'Προγραμματισμός / Επιθεωρήσεις',
      'settings': 'Ρυθμίσεις',
      'faultCount': 'Αριθμός βλαβών',
      'iceWater': 'Πάγος / Νερό',
      'emergencyNumbers': 'Αριθμοί Έκτακτης Ανάγκης',
      'emergencyName': 'Όνομα / Τμήμα',
      'phoneNumber': 'Αριθμός Τηλεφώνου',
      'emergencyCategory': 'Κατηγορία (π.χ. Τεχνικό, Ασφάλεια)',
      'addNumber': 'Προσθήκη Αριθμού',
      'editNumber': 'Επεξεργασία Αριθμού',
      'deleteNumber': 'Διαγραφή Αριθμού',
      'deleteNumberConfirm': 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτόν τον αριθμό;',
      'searchHintNumbers': 'Αναζήτηση με όνομα, αριθμό...',
      'search': 'ΑΝΑΖΗΤΗΣΗ',
      'noNumbers': 'Δεν υπάρχουν αριθμοί για εμφάνιση',
      'noTasks': 'Δεν υπάρχουν εργασίες για εμφάνιση',
      'addTask': 'Προσθήκη Εργασίας',
      'editTask': 'Επεξεργασία Εργασίας',
      'deleteTask': 'Διαγραφή Εργασίας',
      'deleteTaskConfirm': 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτήν την εργασία;',
      'taskTitle': 'Τίτλος Εργασίας',
      'taskType': 'Τύπος Εργασίας / Περιγραφή',
      'currentFailuresTab': 'Τρέχουσες Βλάβες',
      'historyFailuresTab': 'Ιστορικό Βλαβών',
      'productionListDowntime': 'Διακοπή Λίστας Παραγωγής',
      'planningTile': 'Προγραμματισμός / Επιθεωρήσεις',
      'notebookTile': 'Σημειωματάριο',
      'emergencyTile': 'Αριθμοί Έκτακτης Ανάγκης',
      'productionTile': 'Storing List',
      'warehouseTile': 'Αποθήκη',
      'scheduleTile': 'Πρόγραμμα',
      'tasksTile': 'Λίστα Εργασιών',
      'searchMachine': 'ΑΝΑΖΗΤΗΣΗ ΜΗΧΑΝΗΣ',
      'searchHintAssets': 'Αναζήτηση με όνομα, κωδικό ή τοποθεσία...',
      'actions': 'ΕΝΕΡΓΕΙΕΣ',
      'currentTasksTab': 'Τρέχουσες εργασίες',
      'historyTasksTab': 'Ιστορικό εργασιών',
      'delete': 'Διαγραφή',
      'deleteConfirm': 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το στοιχείο;',
      'deleteMachine': 'Διαγραφή μηχανής',
      'deleteNote': 'Διαγραφή σημείωσης',
      'soonAvailable': 'Η δυνατότητα θα είναι σύντομα διαθέσιμη!',
      'linkPath': 'Σύνδεσμος προς τεκμηρίωση ή διαδρομή...',
      'noNotesDisplay': 'Δεν υπάρχουν σημειώσεις για εμφάνιση',
      'dataSentReset': 'Τα δεδομένα έχουν σταλεί και μηδενιστεί.',
      'errorFinalizing': 'Σφάλμα κατά την οριστικοποίηση: ',
      'errorSaving': 'Σφάλμα κατά την αποθήκευση: ',
      'saveSuccess': 'Τα δεδομένα αποθηκεύτηκαν με επιτυχία.',
      'editMachine': 'Επεξεργασία μηχανής',
      'edit': 'Επεξεργασία',
      'searchHintNotes': 'Αναζήτηση στις σημειώσεις...',
      'noDataToSave': 'Δεν υπάρχουν δεδομένα για αποθήκευση.',
      'entry': 'Καταχώρηση',
      'newProductionEntry': 'Νέα καταχώρηση παραγωγής',
      'listEmptyAddWithPlus': 'Η λίστα είναι κενή. Προσθέστε καταχώρηση με το κουμπί +.',
      'date': 'Ημερομηνία',
      'productionReportTitle': 'Storing List',
      'realizedProduction': 'Πραγματοποιηθείσα παραγωγή',
      'chlorineMeasurement': 'Μέτρηση χλωρίου',
      'endOfShiftChecklist': 'Λίστα ελέγχου τέλους βάρδιας',
      'commentsAndDetails': 'Σχόλια και λεπτομέρειες',
      'barrelsEmpty': 'Οι κάδοι απορριμμάτων είναι άδειοι',
      'machineClean': 'Το μηχάνημα είναι καθαρό γύρω-γύρω',
      'nozzlesPierced': 'Τα ακροφύσια τρυπήθηκαν',
      'startTime': 'Ώρα έναρξης',
      'endTime': 'Ώρα λήξης',
      'pauseDowntime': 'Παύση / Διακοπή',
      'cartCount': 'Αριθμός καροτσιών',
      'totalCarts': 'Σύνολο καροτσιών',
      'totalBarrels': 'Σύνολο βαρελιών',
      'chlorineLevel': 'Χλώριο (Cl²)',
      'fustType': 'Τύπος βαρελιού',
      'helpOperator': 'Βοηθός χειριστή',
      'addName': 'Προσθήκη ονόματος',
      'addBarrelType': 'Προσθήκη τύπου βαρελιού',
      'confirmAddLargeAmount': 'Είστε σίγουροι ότι θέλετε να προσθέσετε 15 καρότσια ταυτόχρονα;',
      'confirm': 'Επιβεβαίωση',
      'barrelsPerCart': 'Βαρέλια ανά καρότσι',
      'doubleWashForbidden': 'Σημείωση: Απαγορεύεται το διπλό πλύσιμο των ραφιών.',
      'manageNames': 'Διαχείριση ονομάτων',
      'editName': 'Επεξεργασία ονόματος',
      'manageBarrelTypes': 'Διαχείριση τύπων βαρελιών',
      'editBarrelType': 'Επεξεργασία τύπου βαρελιού',
      'multiplier': 'Πολλαπλασιαστής',
      'confirmDelete': 'Επιβεβαίωση διαγραφής',
      'deleteConfirmMessage': 'Είστε σίγουροι ότι θέλετε να διαγράψετε;',
      'listEmpty': 'Η λίστα είναι κενή',
    },
  };

  String t(String key) {
    final lang = _translations[locale.languageCode] ?? _translations['en']!;
    return lang[key] ?? _translations['en']![key] ?? key;
  }
}
